sudo: false

language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - git clone https://bitbucket.org/osmanov/pecl-eio;
    pushd pecl-eio;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=eio.so" >> "$(php -r 'echo php_ini_loaded_file();')";
  - curl -LS https://github.com/libuv/libuv/archive/v1.6.1.tar.gz | tar -xz;
    pushd libuv-*;
    ./autogen.sh;
    ./configure --prefix=$(dirname `pwd`)/libuv;
    make;
    make install;
    popd;
    git clone https://github.com/bwoebi/php-uv.git;
    pushd php-uv;
    phpize;
    ./configure --with-uv=$(dirname `pwd`)/libuv;
    make;
    make install;
    popd;
    echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')";
  - composer self-update
  - composer install

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - composer require satooshi/php-coveralls:dev-master
  - php vendor/bin/coveralls -v

cache:
  directories:
    - $HOME/.composer/cache
